### ISSUE TITLE
Too long URIs are not accepted

### ISSUE THREAD

**Issue by leucoryx** [rdmorganiser/rdmo#242]
The import of an option.xml failed with the error message:

`Traceback (most recent call last):
  File "/home/rdmouser/rdmo-app/env2/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.StringDataRightTruncation: value too long for type character varying(256)

...
 File "/home/rdmouser/rdmo-app/env2/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.DataError: value too long for type character varying(256)`

The URIs of the options were too long. Does it make sense to change the data type? (So far we used only numbers for the options.)

**Comment by leucoryx** [comment]
The english titles were too long, not the URIs.
