### ISSUE TITLE
[2.0.2 systemd gunicorn] AttributeError: 'AnonymousUser' object has no attribute 'role'

### ISSUE THREAD

**Issue by Commifreak** [rdmorganiser/rdmo#835]
### Description / Beschreibung

Ive upgraded to RDMO2 and made all migrations and adaptations. After first test, we only get this error:

```
[2023-11-20 11:40:32,539] ERROR: Internal Server Error: /
Traceback (most recent call last):
  File "/home/rdmo/env/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/rdmo/env/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rdmo/env/lib/python3.10/site-packages/rdmo/core/views.py", line 35, in home
    return render(request, 'core/home.html', {
  File "/home/rdmo/env/lib/python3.10/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/rdmo/env/lib/python3.10/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/rdmo/env/lib/python3.10/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/rdmo/env/lib/python3.10/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/home/rdmo/env/lib/python3.10/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/rdmo/env/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/rdmo/env/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/rdmo/env/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/rdmo/env/lib/python3.10/site-packages/django/template/loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "/home/rdmo/env/lib/python3.10/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/rdmo/env/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/rdmo/env/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/rdmo/env/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/rdmo/env/lib/python3.10/site-packages/django/template/loader_tags.py", line 208, in render
    return template.render(context)
  File "/home/rdmo/env/lib/python3.10/site-packages/django/template/base.py", line 177, in render
    return self._render(context)
  File "/home/rdmo/env/lib/python3.10/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/rdmo/env/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/rdmo/env/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/rdmo/env/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/rdmo/env/lib/python3.10/site-packages/django/template/library.py", line 237, in render
    output = self.func(*resolved_args, **resolved_kwargs)
  File "/home/rdmo/env/lib/python3.10/site-packages/rules/templatetags/rules.py", line 18, in has_perm
    return user.has_perm(perm, obj)
  File "/home/rdmo/env/lib/python3.10/site-packages/django/contrib/auth/models.py", line 480, in has_perm
    return _user_has_perm(self, perm, obj=obj)
  File "/home/rdmo/env/lib/python3.10/site-packages/django/contrib/auth/models.py", line 220, in _user_has_perm
    if backend.has_perm(user, perm, obj):
  File "/home/rdmo/env/lib/python3.10/site-packages/rules/permissions.py", line 31, in has_perm
    return has_perm(perm, user, *args, **kwargs)
  File "/home/rdmo/env/lib/python3.10/site-packages/rules/permissions.py", line 23, in has_perm
    return permissions.test_rule(name, *args, **kwargs)
  File "/home/rdmo/env/lib/python3.10/site-packages/rules/rulesets.py", line 6, in test_rule
    return name in self and self[name].test(*args, **kwargs)
  File "/home/rdmo/env/lib/python3.10/site-packages/rules/predicates.py", line 172, in test
    return bool(self._apply(*args))
  File "/home/rdmo/env/lib/python3.10/site-packages/rules/predicates.py", line 235, in _apply
    result = self.fn(*callargs)
  File "/home/rdmo/env/lib/python3.10/site-packages/rules/predicates.py", line 184, in OR
    return self._combine(other, operator.or_, args)
  File "/home/rdmo/env/lib/python3.10/site-packages/rules/predicates.py", line 206, in _combine
    self_result = self._apply(*args)
  File "/home/rdmo/env/lib/python3.10/site-packages/rules/predicates.py", line 235, in _apply
    result = self.fn(*callargs)
  File "/home/rdmo/env/lib/python3.10/site-packages/rdmo/management/rules.py", line 12, in is_editor
    return user.role.editor.exists()
AttributeError: 'AnonymousUser' object has no attribute 'role'
```

### Expected behaviour / Erwartetes Verhalten
The RDMO start page

### Context / Kontext

Ubuntu 22.04.3
Python 3.10
RDMO 2.0.2

### References / Verweise

*

**Comment by jochenklar** [comment]
Hi @Commifreak , can you check if you have an "old" `base_navigation.html` in your theme, which checks for permissions for the different elements. The new version should look like this: https://github.com/rdmorganiser/rdmo/blob/master/rdmo/core/templates/core/base_navigation.html#L22

We need to update the upgrade documentation.

**Comment by Commifreak** [comment]
Yep, that was the issue. I replaced `has_perm` with `test_rule` and it did the trick.

**Comment by jochenklar** [comment]
The docs should now be up-to-date: https://rdmo.readthedocs.io/en/latest/upgrade/index.html#upgrade-to-version-2-0-0.

There was also an issue if you use your own `core/base.html`.
